apiVersion: v1
description: Palatable enables reminiscence about food.
name: palatable
version: 0.1.0
dependencies:
  - name: postgresql
    version: 8.6.4
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: postgresql.createChart
