---
apiVersion: v1
kind: Service
metadata:
  name: palatable
  labels:
    app: palatable
spec:
  selector:
    app: palatable
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
