openapi: 3.0.3
info:
  title: palatable
  version: 0.1.0
paths:
  /restaurant:
    get:
      summary: Retrieve a restaurant entry.
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
          description: Name of the restaurant.
      responses:
        200:
          description: Successfully returned restaurant.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Restaurant"
        500:
          description: Database error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a restaurant entry.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Restaurant"
      responses:
        201:
          description: A restaurant, cafe, bar, etc.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Restaurant"
        400:
          description: Bad request body.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        422:
          description: Unparseable body content.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: Database error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Restaurant:
      properties:
        name:
          type: string
          description: Name of the restaurant, cafe, bar, etc.
          example: Theo's Pizzeria
    Error:
      properties:
        detail:
          type: string
          description: Error message returned by application.
          example: no name query parameter provided
        status:
          type: integer
          description: HTTP status code of the error
          example: 400
